Repository harmonyland/harmony, pull requests merged in 2020-12, with the labels that each got.

#47 feat(jsdoc): Added (almost) complete JSDoc comments
  mod.ts
  src/gateway/handlers/channelPinsUpdate.ts
  src/gateway/handlers/guildDelete.ts
  src/gateway/handlers/guildUpdate.ts
  src/gateway/handlers/index.ts
  src/gateway/index.ts
  src/managers/base.ts
  src/managers/baseChild.ts
  src/managers/channels.ts
  src/managers/emojis.ts
  src/managers/gatewayCache.ts
  src/managers/reactionUsers.ts
  src/managers/users.ts
  src/models/cacheAdapter.ts
  src/models/client.ts
  src/models/command.ts
  src/models/commandClient.ts
  src/models/extensions.ts
  src/models/rest.ts
  src/models/voice.ts
  src/structures/base.ts
  src/structures/cdn.ts
  src/structures/channel.ts
  src/structures/dmChannel.ts
  src/structures/emoji.ts
  src/structures/groupChannel.ts
  src/structures/guild.ts
  src/structures/guildCategoryChannel.ts
  src/structures/guildNewsChannel.ts
  src/structures/guildVoiceChannel.ts
  src/structures/invite.ts
  src/structures/member.ts
  src/structures/message.ts
  src/structures/role.ts
  src/structures/snowflake.ts
  src/structures/textChannel.ts
  src/structures/user.ts
  src/structures/voiceState.ts
  src/test/cmd.ts
  src/test/config.ts.sample
  src/utils/bitfield.ts
  src/utils/buildInfo.ts
  src/utils/collection.ts
  src/utils/delay.ts
  src/utils/getChannelByType.ts
  src/utils/intents.ts
  src/utils/permissions.ts
Labels: documentation 📔, enhancement ✨

#46 feat(user): add avatarURL and defaultAvatarURL
  src/structures/cdn.ts
  src/structures/user.ts
Labels: enhancement ✨

#53 fix: minor grammar/typo fixes in comments
  src/managers/base.ts
  src/managers/channels.ts
  src/managers/emojis.ts
  src/models/cacheAdapter.ts
  src/models/client.ts
  src/models/commandClient.ts
  src/models/extensions.ts
  src/models/rest.ts
  src/structures/guild.ts
  src/structures/member.ts
  src/structures/message.ts
  src/structures/webhook.ts
  src/types/gateway.ts
  src/types/guild.ts
  src/types/voice.ts
  src/utils/collection.ts
Labels: bug 🐛, documentation 📔

#54 feat(decorators): added support for decorated events and commands
  mod.ts
  src/gateway/handlers/ready.ts
  src/models/client.ts
  src/models/command.ts
  src/models/commandClient.ts
  src/models/extensions.ts
  src/structures/guildVoiceChannel.ts
  src/structures/message.ts
  src/test/class.ts
Labels: enhancement ✨

#59 update collection methods
  src/utils/collection.ts
Labels: enhancement ✨

#56 feat: Slash Commands & Interactions [WIP?]
  .gitignore
  mod.ts
  src/gateway/handlers/index.ts
  src/gateway/handlers/interactionCreate.ts
  src/gateway/index.ts
  src/models/client.ts
  src/models/commandClient.ts
  src/models/rest.ts
  src/models/slashClient.ts
  src/models/slashModule.ts
  src/structures/presence.ts
  src/structures/slash.ts
  src/structures/voiceState.ts
  src/structures/webhook.ts
  src/test/index.ts
  src/test/music.ts
  src/test/slash-cmd.ts
  src/test/slash.ts
  src/types/endpoint.ts
  src/types/gateway.ts
  src/types/slash.ts
  src/types/userFlags.ts
  src/types/voice.ts
Labels: enhancement ✨

#61 Add Sub Commands and Sub Command Group handlers and decorators
  src/gateway/handlers/index.ts
  src/models/client.ts
  src/models/command.ts
  src/models/commandClient.ts
  src/models/shard.ts
  src/models/slashClient.ts
  src/structures/slash.ts
  src/test/music.ts
  src/test/slash-cmd.ts
  src/test/slash.ts
  src/types/slash.ts
Labels: enhancement ✨

#63 Add Sticker Feature (related to #62)
  src/structures/message.ts
  src/structures/messageSticker.ts
  src/test/index.ts
  src/types/channel.ts
Labels: enhancement ✨

#64 Fix managers' array function
  src/managers/base.ts
  src/managers/channels.ts
  src/managers/guildVoiceStates.ts
  src/managers/members.ts
  src/managers/messageReactions.ts
  src/managers/messages.ts
  src/managers/presences.ts
  src/test/index.ts
Labels: bug 🐛

#65 Add channel edit feature
  mod.ts
  src/gateway/handlers/guildIntegrationsUpdate.ts
  src/managers/guildChannels.ts
  src/structures/guildCategoryChannel.ts
  src/structures/guildNewsChannel.ts
  src/structures/guildVoiceChannel.ts
  src/structures/textChannel.ts
  src/test/index.ts
  src/types/channel.ts
  src/utils/getChannelByType.ts
Labels: enhancement ✨

#66 SlashClient & RESTManager can run alone and added APIMap
  src/gateway/index.ts
  src/models/client.ts
  src/models/rest.ts
  src/models/slashClient.ts
  src/test/music.ts
  src/test/slash-only.ts
Labels: enhancement ✨

#69 feat: add template structure and methods
  src/structures/template.ts
  src/types/template.ts
Labels: enhancement ✨

#73 refactor(gateway): use switch-case to avoid repetitive code
  src/gateway/index.ts
Labels: enhancement ✨

#75 feat: add Invite#delete() method
  src/structures/invite.ts
Labels: enhancement ✨

#76 refactor: move snowflake.ts to utils
  mod.ts
  src/utils/snowflake.ts
Labels: bug 🐛

#70 deps: segregate third-party deps to deps.ts file
  deps.ts
  mod.ts
  src/gateway/index.ts
  src/managers/guildEmojis.ts
  src/models/cacheAdapter.ts
  src/models/client.ts
  src/models/command.ts
  src/models/shard.ts
  src/structures/webhook.ts
  src/test/music.ts
Labels: enhancement ✨

#67 feat: HTTP based Slash Commands util
  README.md
  src/models/client.ts
  src/models/rest.ts
  src/models/slashClient.ts
  src/structures/message.ts
  src/structures/textChannel.ts
  src/test/music.ts
  src/test/slash-only.ts
  src/types/guild.ts
  src/types/slash.ts
Labels: enhancement ✨

#68 Add `addReaction` and `removeReaction` feature, Handle null-id emojis
  src/gateway/handlers/guildEmojiUpdate.ts
  src/gateway/handlers/messageReactionAdd.ts
  src/gateway/handlers/messageReactionRemove.ts
  src/gateway/handlers/messageReactionRemoveEmoji.ts
  src/managers/guildEmojis.ts
  src/managers/messageReactions.ts
  src/structures/emoji.ts
  src/structures/message.ts
  src/structures/textChannel.ts
  src/test/index.ts
  src/types/emoji.ts
Labels: enhancement ✨

#80 Change the event typing way and add <Client>.waitFor method
  src/gateway/handlers/index.ts
  src/models/client.ts
  src/test/index.ts
Labels: enhancement ✨

#74 feat(structures): add Emoji methods
  src/gateway/handlers/guildEmojiUpdate.ts
  src/gateway/handlers/messageReactionAdd.ts
  src/gateway/handlers/messageReactionRemove.ts
  src/gateway/handlers/messageReactionRemoveEmoji.ts
  src/managers/guildEmojis.ts
  src/managers/messageReactions.ts
  src/structures/emoji.ts
  src/types/emoji.ts
Labels: enhancement ✨

#77 feat: add Role#tags prop
  src/structures/role.ts
  src/types/role.ts
Labels: enhancement ✨

#78 feat: new rest methods
  src/managers/base.ts
  src/managers/guildChannels.ts
  src/managers/invites.ts
  src/managers/memberRoles.ts
  src/managers/members.ts
  src/managers/messageReactions.ts
  src/managers/roles.ts
  src/models/client.ts
Labels: enhancement ✨

#79 Fix JSDoc, typo and using before initialization.
  .gitignore
  src/gateway/handlers/index.ts
  src/models/cacheAdapter.ts
  src/models/command.ts
  src/models/extensions.ts
  src/models/shard.ts
  src/structures/member.ts
  src/test/cmds/addemoji.ts
  src/types/channel.ts
  src/types/endpoint.ts
  src/utils/delay.ts
  src/utils/intents.ts
Labels: bug 🐛
